version: '3.4'

services:

  catalogdb:
    image: mongo

  redis:
    image: bitnami/redis

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile

  postgres:
    image: postgres

  adminer:
    image: adminer

volumes:
  catalogdb_data:
  portainer_data:
  postgres_data:
