version: '3.4'

services:

  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  redis:
    image: bitnami/redis
    container_name: redis
    command: redis-server --requirepass password
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  portainer:
    container_name: portiner
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

  catalog.api:
    container_name: catalog.api
    depends_on:
      - catalogdb 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://admin:admin@catalogdb:27017"
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basket.api:
    container_name: basket.api
    depends_on:
      - redis 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5002:80"
      - "5003:443"

  discount.api:
    container_name: discount.api
    depends_on:
      - postgres 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=Server=postgres;Port=5432;Database=DiscountDb;User Id=admin;Password=example;"
    ports:
      - "5004:80"
      - "5005:443"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=postgres;Port=5432;Database=DiscountDb;User Id=admin;Password=example;"
    depends_on:
      - postgres
    ports:
      - "8082:80"

  postgres:
    container_name: postgres
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: DiscountDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
